### PR TITLE
fix: subscriptions wording fix

### LINKED ISSUE #1278: 前端無法正常顯示退款訂單狀態
1. 因為 FB login 問題我們主動退費，根據 design doc，paymentRecord.status = Refunded & subscription.status = Failed 的時候，前端要顯示 `退費`
2. 然而，現在的我的方案頁面，graphql API 並沒有去拿 paymentRecord.status，表格取值只看 subscription.status，並無法分辨是否為退費
3. 有我們主動進行退費的用戶反應，我的方案頁面變成失敗，而非退費。造成誤會

### PR DESCRIPTION
**Pull request by mark86092**
Close #1278

### CODE REVIEW

**Comment by mark86092** [comment]
image

File: src/components/Me/SubscriptionsPage.js [hunk 1]
```diff
@@ -28,11 +30,19 @@ const formatDuration = ({ startedAt, expiredAt }) => (
...
-  </span>
-);
+const formatStatus = (status, d) => {
+  let text = subscriptionStatusWording[status];
+  if (
+    status === SubscriptionStatus.FAILED &&
+    d.paymentRecord &&
+    d.paymentRecord.status === PaymentRecordStatus.refunded
+  ) {
+    text = '退款';
```
Comment (peteranny) [inline src/components/Me/SubscriptionsPage.js:40]: 也可以放進constant裡面
```suggestion
    text = subscriptionRefundedWording;
```

**Review by peteranny — APPROVED** [review]
Pre-approved with one comment
