### PR TITLE
fix: form submit issue on Brave browser

### LINKED ISSUE #1465: Brave 瀏覽器無法正常上傳表單
Source:
- Reported by user via facebook fan page

Statistics: 
- Brave browser Daily Actively User: 30 million  (global)
- All internet users: 5.5 billion 
- Roughly 0.5% of users are using it, maybe in Taiwan the percentage is higher
- We are not able to measure it by google analytics because Brave browser will block it.

### PR DESCRIPTION
**Pull request by barry800414**
Close #1465 

## 這個 PR 是？ 

- fix the issue that user cannot submit form on Brave browser

## 我應該如何手動測試？ 

- [ ] use chrome browser, submit interview / salary / work successfully, check the API request body contains `ga_user_pseudo_id`
- [ ] use brave browser, submit interview / salary / work successfully

### CODE REVIEW

**Review by peteranny — APPROVED** [review]
Surprisingly

File: src/utils/GAUtils.js [hunk 1]
```diff
@@ -11,9 +11,16 @@ export const getUserPseudoId = ga_measurement_id => {
   return new Promise((resolve, reject) => {
     try {
       if (typeof window !== 'undefined' && typeof window.gtag !== 'undefined') {
-        window.gtag('get', ga_measurement_id, 'client_id', field =>
-          resolve(field),
-        );
+        window.gtag('get', ga_measurement_id, 'client_id', resolve);
+        /* 
+          In Brave browser, window.gtag execution will be terminated without 
+          throwing error, so this promise will not never being resolved or rejected.
```
Comment (mark86092) [inline src/utils/GAUtils.js:17]: It looks like window.gtag will call callback (`resolve`) in infinite time, so we add timeout here?

Suggest from chatgpt, remember to add `clearTimeout` to clear the timer memory

```js
const t = setTimeout(() => {
          console.error('Unable to resolve GA User Pseudo Id');
          resolve(null);
        }, 500);

window.gtag('get', ga_measurement_id, 'client_id', field => { clearTimeout(t); resolve(field); });
```

Comment (barry800414) [reply src/utils/GAUtils.js:16]: Nice suggestion, updated and tested
- [x] use chrome browser, submit interview / salary  successfully, check the API request body contains ga_user_pseudo_id
- [x] use brave browser, submit interview / salary  successfully

**Review by mark86092 — APPROVED** [review]
